dataset:
  # Root folder containing the raw sources (fictional example path)
  root: "/home/g-brandao/workspace/crf-data"

  # Subfolders within root
  v3_subfolder: "v3"
  metadata_subfolder: "metadata"

  # Selection of protocols and candidate columns
  protocols: ["obk1"]

  hr_columns:
    - "cola-gw6_polar_hr"
    - "cola-gw6_vo2max_hr"
    - "cola-gw5_polar_hr"
    - "cola-gw5_vo2max_hr"

  speed_columns:
    - "cola-gw6_gps_speed"
    - "cola-gw6_vo2max_gps-speed"
    - "cola-gw5_gps_speed"
    - "cola-gw5_vo2max_gps-speed"

  # Where artifacts are written (Cookiecutter DS: data/raw for ingested artifacts)
  outputs:
    merged_metadata_parquet: "data/raw/merged_metadata.parquet"
    raw_data_parquet: "data/raw/raw_data.parquet"