### conf/project.yaml file

general:
  experiment_name: "[FMK-74] AT Cycling g.brandao"
  target_column: at
  index_column: idx
  models_path: conf/models.yaml
  splits_path: conf/splits.yaml
  ecg_path: data/external/ecg.csv
  columns:
    demographics: [gender, age, height, weight, bmi_class, bmi]
    demographics_derived: [ftp_anthropometric, vo2max_myers, relative_body_fat, age_hr_max]
    gain: [gain_mean, gain_std, percentile_gain, gain_inverse, gain_inverse_relative]
    calculated_bmi: [smm, bfm, ffm, tbw, ffmi, bmr, pbf, smi, tbwDffm]
    ecg: [hr_rest] # , pr_interval, qrs_duration, qt_qtc, prt_axes, p_duration, rr_pp_interval]
    hr: [hr_mean, hr_std, percentile_hr]
    speed: [speed_mean, speed_std]
    speed_derived: [linear_momentum, kinetic_energy]

data_load:
  db_path: /home/g-brandao/workspace/crf-data
  protocol_list:
    - obk1
  device: gw6
  labels:
    hr: hr
    speed: speed_gps
    power: garmin-sports_power
  output_path: data/raw
  exercise: cycling
  droplist: True
  augmentation: True
  augmentation_n: 2
  augmentation_seed: 42

processing:
  input: data/raw
  output: data/interim
  algorithm: ftp-cycling

features:
  input: data/interim
  output: data/features
  train_test_split: True
  dropna: True
  steps:
    binned: True
    combine_num: True
    combine_cat: True
    combine_num_cat: False
    target_encoding: True
    ohe: False
    pca:
      enabled: False
      n_components: 10
  use_cols:
    demographics: True
    demographics_derived: False
    gain: True
    calculated_bmi: False
    ecg: True
    hr: True
    speed: True
    speed_derived: True

selection:
  input: data/features
  output: artifacts/feature_selection
  bootstrap_iters: 20
  stable_n_feats: 60
  n_feats: 15
  models:
    - linear_regression
    - random_forest
    # - xgboost
    # - lgbm
    # - catboost
    # - knn
    # - adaboost
    # - bayesian_ridge
    - elasticnet
    # - ridge
    - gradient_boosting
    # - lasso

train:
  input: data/features
  feature_counts: [5, 10, 15]
  normalize: True
  models:
    - linear_regression
    - elasticnet
    - random_forest
    - extra_trees
    - gradient_boosting
    - xgboost
    - catboost
    - knn 
    - ridge
    - mlp
    - svr
    - gaussian_process
